import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import "./globals.css";
import { TRPCReactProvider } from "./api/trpc/client";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that sets up global providers and structure for the Next.js app.
 *
 * Wraps the application with Nuqs and tRPC React providers, applies the Inter font and antialiasing, and includes a global toast notification system.
 *
 * @param children - The content to be rendered within the layout
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
      <TRPCReactProvider>
      <html lang="en">
      <body
        className={`${inter.className}antialiased`}
      > 
        <Toaster/>
        {children}

      </body>
    </html>
    </TRPCReactProvider>
    </NuqsAdapter>
  );
}
